"use strict";
const assert = require("node:assert/strict");
const { launch, example, partial, C } = require("./test_inventory_catalogue.cjs");
const V = "catalogue-data-bridge/v1", S = "01234567-89ab-cdef-0123-456789abcdef";
const id = n => `00000000-0000-0000-0000-${String(n).padStart(12, "0")}`;
const checks = [];
(async () => {
  const normal = await launch();
  assert.equal(normal.dom.window.DiskCatalogueNativeBridge, undefined);
  normal.dom.window.close();
  checks.push("standalone catalogue has no native ingress");
  const a = await launch({ embedded: true }), { d, dom } = a, B = dom.window.DiskCatalogueNativeBridge;
  assert.ok(Object.isFrozen(B));
  assert.equal(Object.getOwnPropertyDescriptor(dom.window, "DiskCatalogueNativeBridge").writable, false);
  assert.deepEqual(Object.keys(B).sort(), ["initialise", "retire", "stage"]);
  ["open-inventory", "save-catalogue", "inventory-file", "prepare-plan", "catalogue-saved"].forEach(x => {
    assert.equal(d.getElementById(x).hidden, true); assert.equal(d.getElementById(x).disabled, true);
  });
  assert.match(a.text(), /Open, Save and manual-plan export are unavailable/);
  assert.equal(d.querySelectorAll('a[href]:not([href^="#"])').length, 0);
  assert.equal(dom.window.webkit, undefined);
  checks.push("embedded mode exposes data-only fixed functions and explicitly unavailable controls");
  // The shared harness deliberately stubs anchor.click for download interception.
  d.querySelector(".skip-link").dispatchEvent(new dom.window.MouseEvent("click", { bubbles: true, cancelable: true }));
  assert.equal(d.activeElement.id, "catalogue");
  assert.equal(dom.window.location.hash, "");
  checks.push("embedded skip link moves focus without navigation");
  let reads = 0;
  await a.file(example, { file: { size: 12, arrayBuffer: () => { reads++; throw Error("must not read"); } } });
  assert.equal(reads, 0); assert.equal(a.cards().length, 0);
  a.click("open-inventory"); a.click("save-catalogue"); a.click("prepare-plan");
  assert.equal(a.downloads.length, 0);
  checks.push("embedded file events and unavailable export controls have no read or download path");
  assert.throws(() => B.stage(V, S, id(1), example));
  for (const [v, s] of [["next", S], [V, "invalid"], [V, null]]) assert.throws(() => B.initialise(v, s));
  const ready = B.initialise(V, S); assert.equal(ready.state, "ready");
  assert.throws(() => B.initialise(V, S));
  checks.push("session initialisation is explicit, bounded and one-use");
  for (const [v, s, i] of [["next", S, id(1)], [V, id(99), id(1)], [V, S, "bad"]])
    assert.throws(() => B.stage(v, s, i, example));
  assert.equal(a.cards().length, 0);
  checks.push("wrong versions, sessions and delivery shapes do not stage");
  const bad = ["", null, "{}", example.replace('"schema_version":', '"schema_version":"duplicate","schema_version":'),
    "\ufeff" + example, C.exportCatalogue(C.empty()), " ".repeat(C.LIMITS.snapshotBytes + 1),
    "é".repeat(C.LIMITS.snapshotBytes / 2 + 1)];
  for (const text of bad) assert.throws(() => B.stage(V, S, id(1), text));
  assert.equal(d.getElementById("catalogue-dialog").open, false);
  checks.push("same strict parser rejects malformed, duplicate, BOM, catalogue and byte-oversized input");
  const staged = B.stage(V, S, id(1), example);
  assert.equal(staged.state, "staged"); assert.equal(a.cards().length, 0);
  assert.equal(d.getElementById("catalogue-dialog").open, true);
  assert.equal(d.activeElement.id, "catalogue-name");
  assert.match(d.getElementById("catalogue-dialog-intro").textContent, /unauthenticated/);
  assert.throws(() => B.stage(V, S, id(2), partial));
  checks.push("delivery stages the shared preview, focuses its label and blocks overlapping delivery");
  assert.throws(() => B.retire(V, S, id(2)));
  assert.equal(d.getElementById("catalogue-dialog").open, true);
  const cancelled = B.retire(V, S, id(1));
  assert.equal(cancelled.outcome, "cancelled");
  assert.equal(d.getElementById("catalogue-dialog").open, false);
  a.submit(); assert.equal(a.cards().length, 0);
  assert.equal(B.retire(V, S, id(1)), cancelled);
  assert.throws(() => B.stage(V, S, id(1), example));
  checks.push("retirement fence closes only matching preview and prevents later Add/replay");
  B.stage(V, S, id(2), example); a.submit(); a.submit();
  assert.equal(a.cards().length, 1);
  assert.match(d.getElementById("catalogue-status").textContent, /temporary native preview · nothing saved/);
  assert.equal(B.retire(V, S, id(2)).outcome, "committed");
  assert.equal(a.cards().length, 1);
  checks.push("Add before retirement remains one committed historical record");
  B.stage(V, S, id(3), partial); a.click("catalogue-cancel");
  assert.equal(B.retire(V, S, id(3)).outcome, "dismissed");
  assert.equal(a.cards().length, 1);
  checks.push("Cancel dismisses preview without affecting historical records");
  B.stage(V, S, id(4), partial); a.click("catalogue-close");
  d.querySelector(".source-card .text-button").click();
  const title = d.getElementById("catalogue-dialog-title").textContent;
  assert.equal(B.retire(V, S, id(4)).outcome, "dismissed");
  assert.equal(d.getElementById("catalogue-dialog").open, true);
  assert.equal(d.getElementById("catalogue-dialog-title").textContent, title);
  assert.throws(() => B.stage(V, S, id(5), partial));
  a.click("catalogue-cancel");
  checks.push("late retirement preserves a newer rename dialog and busy edits reject delivery");
  const hostile = JSON.parse(partial); hostile.source.label = 'Shelf <img src=x onerror=alert(1)> " \\u2028';
  B.stage(V, S, id(5), JSON.stringify(hostile)); a.submit();
  assert.equal(B.retire(V, S, id(5)).outcome, "committed");
  assert.equal(a.cards().length, 2); assert.equal(d.querySelectorAll("img").length, 0);
  assert.match(a.text(), /<img src=x onerror=alert\(1\)>/);
  assert.equal(d.getElementById("save-catalogue").disabled, true);
  assert.equal(d.getElementById("save-catalogue").hidden, true);
  checks.push("hostile strings remain inert after shared Add and embedded export stays unavailable");
  a.click("choose-comparison"); a.submit();
  assert.equal(d.getElementById("comparison-view").hidden, false);
  assert.match(a.text(), /Matching names and sizes do not prove identical contents or a backup/);
  a.click("clear-comparison");
  assert.equal(d.activeElement.id, "choose-comparison");
  checks.push("two host records use the same comparison and focus-return behaviour");
  B.stage(V, S, id(6), example);
  dom.window.dispatchEvent(new dom.window.Event("pagehide")); a.submit();
  assert.equal(a.cards().length, 2);
  assert.throws(() => B.stage(V, S, id(7), example));
  assert.throws(() => B.retire(V, S, id(6)));
  assert.throws(() => B.initialise(V, S));
  checks.push("navigation permanently invalidates the document session and staged Add");
  assert.deepEqual(a.errors, []); assert.equal(a.downloads.length, 0); dom.window.close();
  const cap = await launch({ embedded: true }), cb = cap.dom.window.DiskCatalogueNativeBridge;
  cb.initialise(V, S);
  for (let i=0;i<128;i++) { cb.stage(V, S, id(i), example); cb.retire(V, S, id(i)); }
  assert.throws(() => cb.stage(V, S, id(128), example), /session is full/);
  assert.equal(cap.cards().length, 0); assert.deepEqual(cap.errors, []); cap.dom.window.close();
  checks.push("128 one-use delivery identifiers is an explicit per-view bound with no replay eviction");
  console.log(`PASS: ${checks.length} native bridge DOM checks\n` + checks.map(x => "  " + x).join("\n"));
})().catch(e => { console.error(e); process.exitCode = 1; });
