"use strict";
const assert=require("node:assert/strict");
const {launch,example,partial,C}=require("./test_inventory_catalogue.cjs");
const V="catalogue-data-bridge/v2",S="12345678-1234-4234-8234-123456789abc";
const id=n=>`00000000-0000-4000-8000-${String(n).padStart(12,"0")}`;
const req=(n,fields={})=>({version:V,session:S,operation:id(n),...fields});
const checks=[];
(async()=>{
 const a=await launch({embedded:true}),{d,dom}=a,B=dom.window.DiskCatalogueNativeBridge;
 assert.throws(()=>B.initialise(V,S));assert.throws(()=>B.initialise(V,S,"writable"));
 assert.equal(B.initialise(V,S,"owned-storage").mode,"owned-storage");
 assert.match(a.text(),/temporary test library storage/);assert.doesNotMatch(d.getElementById("native-preview-note").textContent,/Open, Save.*unavailable/);
 assert.equal(dom.window.webkit,undefined);assert.equal(d.getElementById("save-catalogue").hidden,true);
 checks.push("owned mode exposes honest native-storage copy without a JS-to-native or download channel");
 function add(text,n){B.stage(V,S,id(n),text);a.submit();assert.equal(B.retire(V,S,id(n)).outcome,"committed");}
 add(example,1000);add(partial,1001);assert.equal(a.cards().length,2);
 assert.match(d.getElementById("catalogue-status").textContent,/save a new library version/);
 const first=B.exportCatalogue(req(1,{fence:""}));assert.equal(C.parse(first.text).records.length,2);
 assert.equal(B.savedResult(req(1)).state,"not-applied");assert.equal(B.status(req(2)).dirty,"dirty");
 B.acknowledgeSaved(req(1,{revision:first.revision}));assert.equal(B.status(req(2)).dirty,"clean");
 checks.push("two historical locations export exactly and only explicit acknowledgement cleans the catalogue");
 const selection=d.querySelector("#catalogue-results input:not(:disabled)");selection.click();
 assert.equal(B.status(req(2)).selections,"1");assert.match(d.getElementById("catalogue-status").textContent,/not included in library saving/);
 const loss=B.prepareClose(req(3));assert.equal(loss.dirty,"clean");assert.equal(loss.selections,"1");assert.equal(loss.state,"fenced");
 assert.equal(d.getElementById("clear-selection").disabled,true);a.click("clear-selection");assert.equal(B.status(req(2)).selections,"1");
 d.getElementById("clear-selection").dispatchEvent(new dom.window.MouseEvent("click",{bubbles:true,cancelable:true}));assert.equal(B.status(req(2)).selections,"1");
 assert.throws(()=>B.stage(V,S,id(1002),example));B.releaseClose(req(3));assert.equal(d.getElementById("clear-selection").disabled,false);
 checks.push("clean catalogue with temporary selections is reported and fenced against pointer/programmatic event mutation");
 d.querySelector(".source-card .text-button").click();const input=d.getElementById("catalogue-name");input.value="Draft preserved · café";input.dispatchEvent(new dom.window.Event("input",{bubbles:true}));
 const draft=B.prepareClose(req(4));assert.equal(draft.dialog,"label-edit");assert.equal(draft.draft,"uncommitted");assert.equal(input.disabled,true);
 assert.throws(()=>B.exportCatalogue(req(5,{fence:id(4)})));a.submit();assert.equal(a.cards()[0].querySelector("h3").textContent.includes("Draft preserved"),false);
 d.getElementById("catalogue-dialog").dispatchEvent(new dom.window.Event("cancel",{bubbles:true,cancelable:true}));assert.equal(d.getElementById("catalogue-dialog").open,true);B.releaseClose(req(4));assert.equal(input.value,"Draft preserved · café");assert.equal(input.disabled,false);assert.equal(d.activeElement,input);a.submit();assert.match(a.cards()[0].textContent,/Draft preserved · café/);
 checks.push("unfinished label draft survives close enquiry/Cancel with focus; committed-data Save cannot discard it");
 const saved=B.exportCatalogue(req(6,{fence:""}));d.querySelector(".source-card .text-button").click();d.getElementById("catalogue-name").value="Newer location name";a.submit();
 assert.equal(B.acknowledgeSaved(req(6,{revision:saved.revision})).state,"earlier-saved");assert.equal(B.status(req(2)).dirty,"dirty");assert.match(a.text(),/newer edits are still unsaved/);assert.equal(B.status(req(2)).selections,"1");
 checks.push("edit-after-export stays dirty and temporary selections survive an older-revision acknowledgement");
 const close=B.prepareClose(req(7));const closeExport=B.exportCatalogue(req(8,{fence:id(7)}));B.acknowledgeSaved(req(8,{revision:closeExport.revision}));const afterSave=B.status(req(2));assert.equal(afterSave.dirty,"clean");assert.equal(afterSave.selections,"1");assert.equal(afterSave.state,"busy");B.releaseClose(req(7));
 checks.push("Save under a close fence does not release the fence or discard selected project files");
 a.click("choose-comparison");a.submit();assert.equal(d.getElementById("comparison-view").hidden,false);
 const search=d.getElementById("catalogue-search");search.value="Photo";search.dispatchEvent(new dom.window.Event("input",{bubbles:true}));search.focus();
 const before=B.exportCatalogue(req(9,{fence:""}));const opened=B.prepareOpen(req(10));assert.equal(search.disabled,true);
 B.prepareReplacement(req(10,{candidate:id(11),revision:opened.revision,epoch:opened.epoch,text:C.exportCatalogue(C.empty())}));
 assert.equal(a.cards().length,2);B.cancelOpen(req(10));assert.equal(a.cards().length,2);assert.equal(search.value,"Photo");assert.equal(d.getElementById("comparison-view").hidden,false);assert.equal(d.activeElement,search);assert.equal(B.status(req(2)).selections,"1");
 checks.push("cancelled Open preserves exact catalogue, search, comparison, selection and focus");
 const next=B.prepareOpen(req(12));B.prepareReplacement(req(12,{candidate:id(13),revision:next.revision,epoch:next.epoch,text:first.text}));
 const commit=req(12,{candidate:id(13),revision:next.revision,epoch:next.epoch});const committed=B.commitReplacement(commit);assert.equal(committed.state,"committed");assert.equal(committed.view,"ready");
 assert.equal(a.cards().length,2);assert.equal(search.value,"");assert.equal(d.getElementById("comparison-view").hidden,true);assert.equal(B.status(req(2)).selections,"0");assert.equal(B.status(req(2)).dirty,"clean");
 assert.equal(B.commitReplacement(commit).revision,committed.revision);assert.equal(B.cancelOpen(req(12)).state,"committed");assert.equal(B.replacementResult(req(12,{candidate:id(13)})).state,"committed");
 checks.push("explicit replacement commits once, clears only disclosed temporary state and is queryable after lost reply/late Cancel");
 const empty=B.prepareOpen(req(14));B.prepareReplacement(req(14,{candidate:id(15),revision:empty.revision,epoch:empty.epoch,text:C.exportCatalogue(C.empty())}));B.commitReplacement(req(14,{candidate:id(15),revision:empty.revision,epoch:empty.epoch}));assert.equal(a.cards().length,0);assert.equal(d.getElementById("empty-catalogue").hidden,false);
 checks.push("zero-record replacement is a deliberate supported state");
 const last=B.exportCatalogue(req(16,{fence:""}));dom.window.dispatchEvent(new dom.window.Event("pagehide"));assert.throws(()=>B.acknowledgeSaved(req(16,{revision:last.revision})));assert.throws(()=>B.status(req(17)));assert.equal(a.downloads.length,0);assert.deepEqual(a.errors,[]);dom.window.close();
 checks.push("navigation retires every late persistence callback without downloads or native invocation");
 const app=await launch({embedded:true}),AB=app.dom.window.DiskCatalogueNativeBridge;
 assert.throws(()=>AB.initialise(V,S,"application-data "));assert.equal(AB.initialise(V,S,"application-data").mode,"application-data");
 assert.match(app.d.getElementById("native-preview-note").textContent,/Save library versions on this Mac/);assert.doesNotMatch(app.d.getElementById("native-preview-note").textContent,/temporary test library storage/);
 AB.stage(V,S,id(2000),example);app.submit();AB.retire(V,S,id(2000));const appSave=AB.exportCatalogue(req(2001,{fence:""}));assert.equal(C.parse(appSave.text).records.length,1);assert.equal(AB.status(req(2002)).dirty,"dirty");AB.acknowledgeSaved(req(2001,{revision:appSave.revision}));assert.equal(AB.status(req(2002)).dirty,"clean");
 assert.equal(app.dom.window.webkit,undefined);assert.equal(app.d.getElementById("save-catalogue").hidden,true);assert.equal(app.downloads.length,0);assert.deepEqual(app.errors,[]);app.dom.window.close();
 checks.push("application-data copy and data-only Save keep exact admission, strict catalogue parsing and no native/download command channel");
 console.log(`PASS: ${checks.length} native library DOM checks\n`+checks.map(x=>"  "+x).join("\n"));
})().catch(error=>{console.error(error);process.exitCode=1;});
